# Generated by Django 2.2 on 2021-04-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=100)),
                ('subject_id', models.IntegerField()),
                ('paper_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionanswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qna.Papers', verbose_name='Papers')),
            ],
            options={
                'db_table': 'question_answers',
            },
        ),
    ]
