# Generated by Django 2.2 on 2021-04-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=100)),
                ('paper_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.PROTECT, to='curriculum.subjectdetails', verbose_name='Subject')),
            ],
        ),
    ]
