# Generated by Django 2.2.7 on 2021-04-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paper.Subject', verbose_name='Subject'),
        ),
    ]
