# Generated by Django 2.2.7 on 2021-04-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0002_auto_20210404_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.subjectdetails', verbose_name='Subject'),
        ),
    ]
